version: "3"

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecure
      - N8N_ENCRYPTION_KEY=3a7f12948ea4abc8e4890c6c74b1d039
      - TZ=Etc/UTC
    volumes:
      - ./n8n-data:/home/node/.n8n
